<%@ page language="java" import="java.util.*" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/common/inc_ctx.jsp"%>
<%@ include file="/common/inc_css.jsp"%>
<%@ include file="/common/inc_js.jsp"%>
<script type="text/javascript">
</script>
</head>
<body>
<table data-toggle="table" data-striped="true">
	<thead>
	<tr>
		<th style="width:2%"><input id="ckb_all" type="checkbox"/></th>
		<th data-sortable="true">主键</th>
		<th data-sortable="true">外键</th>
		<th data-sortable="true">排序号</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片</th>
		<th>图片_end</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	<tr>
		<td><input name="keyIndex" type="checkbox" value=""/></td>
		<td>col_1</td>
		<td>col_2</td>
		<td>col_3</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
		<td>col_4</td>
	</tr>
	</tbody>
</table>
</body>
</html>

